### ISSUE TITLE
erup-5 migrations

### ISSUE THREAD

**Issue by flipchan** [edgeware-network/edgeware-node#25]
## Pallet migrations to go over:
```
- 00: System
 - 01: Utility
 - 02: Aura
 - 03: Timestamp
 - 04: Authorship
 - 05: Indices
 - 06: Balances
 - 07: TransactionPayment
 - 08: ElectionProviderMultiPhase, Changed place
 - 09: Staking
 - 10: Session
 - 11: Democracy
 - 12: Council
 - 13: PhragmenElection
 - 14: Grandpa
 - 15: Treasury
 - 16: Contracts
 - 17: Sudo
 - 18: ImOnline
 - 19: AuthorityDiscovery
 - 20: Offences
 - 21: Historical
 - 22: RandomnessCollectiveFlip
 - 23: Identity
 - 24: Recovery
 - 25: Vesting
 - 26: Scheduler
 - 27: Proxy
 - 28: Multisig
 - 29: Assets
 - 30: TreasuryReward
 - 31: Ethereum
 - 32: EVM
 - 33: Bounties
 - 34: Tips
 - 35: DynamicFee
 - 36: BaseFee, new
 - 37: BagsList, new
 - 38: Preimage, new
```

current node:
staking.storageVersion: Releases
V4

from erup-5 node:
staking.storageVersion: PalletStakingReleases
V6_0_0

pallet-staking v3.0.0 (https://github.com/webb-tools/substrate.git?branch=erup-4#656e206f)

pallet-staking v4.0.0-dev (https://github.com/paritytech/substrate?branch=polkadot-v0.9.19#174735ea)

**Comment by flipchan** [comment]
scheduler.storageVersion: Releases
V1

**Comment by flipchan** [comment]
transactionPayment.storageVersion: Releases
V2

**Comment by flipchan** [comment]
Erup-5:
vesting.storageVersion: PalletVestingReleases
V0

**Comment by flipchan** [comment]
Reference counting:
https://github.com/paritytech/substrate/blob/19b44f087b30e7730cf037518ec921c336fcbb0f/frame/system/src/migrations/mod.rs#L88


Previous:
https://github.com/webb-tools/substrate/blob/erup-4/frame/system/src/lib.rs#L672

**Comment by flipchan** [comment]
https://crates.parity.io/frame_support/attr.pallet.html#checking-upgrade-guidelines

**Comment by flipchan** [comment]
subwasm metadata -j latest.wasm
subwasm metadata -j erup-4

**Comment by flipchan** [comment]
check bulk:

```python

from os import system                       
                                            
wasmfile = input('Enter wasm file:')        
lista ="""                                  
System                                      
Utility                                     
Aura                                        
Timestamp                                   
Authorship                                  
Indices                                     
Balances                                    
TransactionPayment                          
ElectionProviderMultiPhase                  
Staking                                     
Session                                     
Democracy                                   
Council
PhragmenElection
Grandpa
Treasury
Contracts
Sudo
ImOnline
AuthorityDiscovery
Offences
Historical
RandomnessCollectiveFlip
Identity
Recovery
Vesting
Scheduler
Proxy
Multisig
Assets
TreasuryReward
Ethereum
EVM
Bounties
Tips
DynamicFee
BaseFee 
BagsList
Preimage
"""

def run():
        print('start')
        for x in list(filter(None, lista.split('\n'))):
                x = x.lower()
                print('Pallet', x+":")
                system(str('subwasm metadata -m {module} -j {wasmfile}'.format(module=x, wasmfile=wasmfile)))
        print('finish')

run()


```

**Comment by flipchan** [comment]
New calls on Utility:
dispatch_as
New events:
- 2: ItemCompleted
- 3: DispatchedAs
New Constants:
batched_calls_limit

Balances new call:
- 4: transfer_all
- 5: force_unreserve

Module 07: TransactionPayment
`
🤙 Calls:
📢 Events:
⛔️ Errors:
📦 Storage:
- NextFeeMultiplier
- StorageVersion
💎 Constants:
- OperationalFeeMultiplier
- WeightToFee
- LengthToFee

`
ElectionProviderMultiPhase:
same events

New staking functions:`
- 23: set_staking_configs
- 24: chill_other
- 25: force_apply_min_commission
`
New staking events:`
- 9: StakingElectionFailed
- 10: Chilled
- 11: PayoutStarted
`
Staking Constants(to go throw):`
- MaxNominations
- SessionsPerEra
- BondingDuration
- SlashDeferDuration
- MaxNominatorRewardedPerValidator
- MaxUnlockingChunks
`

Session, same

Democracy new events:`
- 17: Voted
- 18: Seconded
`

Council: same functions


Contracts:`
Removed: claim_surcharge
Added: 
- 3: upload_code
- 4: remove_code
`
Sudo: same calls

Identity, same calls

Recovery: ~

vesting, new call: merge_schedules

proxy: ~

Multisig ~

assets new functions:
`
- 23: touch
- 24: refund
`

Bounties/evm: ~

**Comment by flipchan** [comment]
Utility should be okey:
https://github.com/paritytech/substrate/blob/master/frame/utility/src/lib.rs
https://github.com/webb-tools/substrate/blob/erup-4/frame/utility/src/lib.rs

**Comment by flipchan** [comment]
Storage version releases in erup-5:`
frame/democracy/src/lib.rs:490:			StorageVersion::<T>::put(Releases::V1);
frame/transaction-payment/src/lib.rs:239:		Releases::V1Ancient
frame/transaction-payment/src/lib.rs:338:			StorageVersion::<T>::put(Releases::V2);
frame/vesting/src/lib.rs:98:		Releases::V0
frame/balances/src/lib.rs:583:			<StorageVersion<T, I>>::put(Releases::V2_0_0);
frame/balances/src/lib.rs:740:		Releases::V1_0_0
frame/staking/src/lib.rs:789:		Releases::V8_0_0
frame/staking/src/migrations.rs:50:				StorageVersion::<T>::put(crate::Releases::V9_0_0);`

**Comment by flipchan** [comment]
Latest runtime upgrade was made with Tokyo:
https://github.com/edgeware-network/edgeware-node/releases/tag/v3.2.0

**Comment by flipchan** [comment]
frame/democracy/src/lib.rs:409:		StorageVersion build(|_| Some(Releases::V1)): Option<Releases>;
frame/transaction-payment/src/lib.rs:228:		Releases::V1Ancient
frame/transaction-payment/src/lib.rs:255:		StorageVersion build(|_: &GenesisConfig| Releases::V2): Releases;
frame/scheduler/src/lib.rs:223:			StorageVersion::<T>::put(Releases::V2);
frame/balances/src/lib.rs:617:		Releases::V1_0_0
frame/staking/src/lib.rs:827:		Releases::V6_0_0



### Runtime Storage Versions    

| Pallet Name | Tokyo | Erup-5 |
| ----------- | ----------- | ----------- |
| Staking | not set | not set |
| Balances | not set | not set |
| scheduler | not set | not set |   
| Democracy | not set | not set |

**Comment by flipchan** [comment]
```
./target/release/edgeware try-runtime --chain edgeware --wasm-execution=compiled offchain-worker live --uri ws://127.0.0.1:9989  -s snapshot.bin --at 0x44a48294b3a5d4c60c643c712b58417806c478eb68924bfa889814d4690beabe
2022-09-01 19:19:48.138  INFO main jsonrpsee_client_transport::ws: Connection established to target: Target { sockaddrs: [], host: "127.0.0.1", host_header: "127.0.0.1:9989", _mode: Plain, path_and_query: "/" }
2022-09-01 19:19:48.139  INFO main try-runtime::cli: fetched header from "ws://127.0.0.1:9989", block number: 13286356    
2022-09-01 19:19:48.139  INFO main jsonrpsee_client_transport::ws: Connection established to target: Target { sockaddrs: [], host: "127.0.0.1", host_header: "127.0.0.1:9989", _mode: Plain, path_and_query: "/" }
2022-09-01 19:19:48.139  INFO main remote-ext: scraping key-pairs from remote @ 0x44a48294b3a5d4c60c643c712b58417806c478eb68924bfa889814d4690beabe    
2022-09-01 19:19:48.139  INFO main remote-ext: downloading data for all pallets.    
2022-09-01 19:19:58.424  INFO main remote-ext: adding data for hashed key: 26aa394eea5630e07c48ae0c9558cef7f9cce9c888469bb1a0dceaa129672ef8    
2022-09-01 19:19:58.425  INFO main remote-ext: adding data for hashed key: 3a636f6465    
2022-09-01 19:19:58.865  INFO main remote-ext: 👩‍👦 scraping child-tree data from 5 top keys    
2022-09-01 19:19:58.980  INFO main remote-ext: injecting a total of 80560 top keys    
2022-09-01 19:20:02.087  INFO main remote-ext: injecting a total of 61 child keys    
2022-09-01 19:20:02.249  INFO main remote-ext: initialized state externalities with storage root 0x22fb9a24312365e3090794ceeb1e4f84324a1c393bfca996eefa3853f4d3d18a    
2022-09-01 19:20:04.075  INFO main jsonrpsee_client_transport::ws: Connection established to target: Target { sockaddrs: [], host: "127.0.0.1", host_header: "127.0.0.1:9989", _mode: Plain, path_and_query: "/" }
2022-09-01 19:20:04.075  INFO main try-runtime::cli: found matching spec name: "edgeware"    
2022-09-01 19:20:04.075  INFO main try-runtime::cli: found matching spec version: 46    
2022-09-01 19:20:04.081  INFO main try-runtime::cli: OffchainWorkerApi_offchain_worker executed without errors. 
```

**Comment by ShankarWarang** [comment]
Covered under #28 and merged already.
