### ISSUE TITLE
Bounty: Metadata needs to be updated to v14

### ISSUE THREAD

**Issue by thomivy** [edgeware-network/edgeware-node#4]
Update EDG network to latest metadata version (from v12 to v14) in the upcoming Wako upgrade.

See repo: https://github.com/edgeware-network/edgeware-node

Further Reading:
https://github.com/paritytech/substrate/pull/8615
https://gist.github.com/ascjones/0d81a4c44e84cacd9f714cd34a6de823

Agency will pay $2k in EDG for this.data version (from v12 to v14) in the upcoming Wako upgrade.

**Comment by tdelabro** [comment]
Hey,
I had a talk with Richard and Ramsey about the way my organization can contribute to Edgeware, and while exploring you repository I found this issue.
It sound like something I can easily do. How should we proceed in order for me to claim and execute this bounty. What is the process to contribute ?

**Comment by ShankarWarang** [comment]
Done in #28 and merged already.
