### ISSUE TITLE
No able to perform runtime upgrade from v3.3.3 to v3.5.1

### ISSUE THREAD

**Issue by ashi20192020** [Edgeware-Network/edgeware-node#44]
Hi,

I have been trying to perform runtime upgrade from v3.3.3 to v3.5.1 using this [tutorial](https://docs.substrate.io/tutorials/get-started/upgrade-a-running-network/#submit-a-transaction-to-upgrade-the-runtime) but getting below error in log:

```
2022-11-09 12:06:48 Unable to author block in slot 277998668,. `can_author_with` returned: Failed to get runtime version at `BlockId::Hash(0x0bff470f3ba6fe6bafa7badf7a11586f51759a2fa0f2d1f25389b91a9a7d4a6d)` and will disable authoring. Error: VersionInvalid("RuntimeConstruction(Other(\"host doesn\\\'t provide such function: env:ext_storage_clear_prefix_version_2\"))") Probably a node update is required!  
```

Please let me know what I am missing. Is there any other way to perform upgrade except fresh deployment? I do not want to loose my data.

**Comment by ShankarWarang** [comment]
v3.5.1 won't be able to sync blocks after the upgrade merge (block #14256000). Hence, it is recommended to upgrade your node(s) to v4.0.2 release.

**Comment by ashi20192020** [comment]
@ShankarWarang I am still facing this issue. 

I started node with v3.3.3. and tried to do runtime upgrade to v4.0.2 using this https://docs.substrate.io/tutorials/get-started/upgrade-a-running-network/#submit-a-transaction-to-upgrade-the-runtime

`2022-11-12 16:31:24 Unable to author block in slot 278044514,. `can_author_with` returned: Failed to get runtime version at `BlockId::Hash(0xb8b5b10e199575a53003bc4d9e17eb2deeffc0c1e901d3ef47f2c2894a1eba19)` and will disable authoring. Error: VersionInvalid("RuntimeConstruction(Other(\"host doesn\\\'t provide such function: env:ext_storage_clear_prefix_version_2\"))") Probably a node update is required!    
2022-11-12 16:31:25 💤 Idle (0 peers), best: #10 (0xb8b5…ba19), finalized #8 (0x05dd…22df), ⬇ 0 ⬆ 0    
^
`

**Comment by JelliedOwl** [comment]
HI

> I started node with v3.3.3. and tried to do runtime upgrade to v4.0.2 using this https://docs.substrate.io/tutorials/get-started/upgrade-a-running-network/#submit-a-transaction-to-upgrade-the-runtime

You don't need to run the upgrade TX - the upgrade is already active on-chain.  You need the v4.0.2 node executable rather than trying to use the v3.3.3 one.  Download from here if you haven't already got it, unless you prefer to compile it yourself.  https://github.com/edgeware-network/edgeware-node/releases/tag/v4.0.2

**Comment by ashi20192020** [comment]
@JelliedOwl I may be missing something. 

I have a node running on v3.3.3. Now I want to upgrade it to higher version. Ideally I should do runtime upgrade on my node version wise but @ShankarWarang suggested in above comment that v3.5.1 won't work, so I tried to perform runtime upgrade from v3.3.3 to v4.0.2. 


Sorry I am not able to understand your comment. Are you suggesting to purge the data and start fresh chain with v4.0.2? Please correct me if I am missing anything.

**Comment by JelliedOwl** [comment]
I think one of us is misunderstanding, but perhaps I'm misunderstanding what you're trying to do?

Looking at the error message your getting, it seems to be failing at block 10 in the chain and I don't THINK that block hash is Edgeware (though I'm not certain).

Are you trying to upgrade an Edgeware node from v3.3.3 to v4.0.1 or something else?

**Comment by ashi20192020** [comment]
@JelliedOwl I am running node on a testnet with branch v3.3.3. Now I want to upgrade it to higher version.

**Comment by ayushmishra2005** [comment]
@JelliedOwl Could you please help me on this?
